name: Setup Python and Install uv
description: Sets up Python and installs uv
runs:
    using: composite
    steps:
    -   uses: actions/setup-python@v5
        with:
            python-version: ${{ inputs.python-version }}
    -   name: Install uv
        shell: bash
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
    -   name: Create virtualenv
        shell: bash
        run: uv venv .venv
inputs:
    python-version:
        required: true
        description: Python version to use in the matrix.
